set_property PACKAGE_PIN H19 [get_ports {Link_Activity[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Link_Activity[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {Link_Active[0]}]
set_property PACKAGE_PIN H20 [get_ports {Link_Active[0]}]

set_property IOSTANDARD LVDS_25 [get_ports adc_clk_n]
set_property PACKAGE_PIN AA7 [get_ports adc_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports adc_clk_p]

set_property PULLUP true [get_ports {Link_Active[0]}]
set_property PULLUP true [get_ports {Link_Activity[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports LED_Display_Blank]
set_property IOSTANDARD LVCMOS33 [get_ports LED_Display_Clock]
set_property IOSTANDARD LVCMOS33 [get_ports LED_Display_Data]
set_property IOSTANDARD LVCMOS33 [get_ports LED_Display_Latch]
set_property PACKAGE_PIN A18 [get_ports LED_Display_Blank]
set_property PACKAGE_PIN A17 [get_ports LED_Display_Clock]
set_property PACKAGE_PIN A16 [get_ports LED_Display_Data]
set_property PACKAGE_PIN A19 [get_ports LED_Display_Latch]

set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rf_adc_data[0]}]
set_property PACKAGE_PIN T6 [get_ports {rf_adc_data[15]}]
set_property PACKAGE_PIN R6 [get_ports {rf_adc_data[14]}]
set_property PACKAGE_PIN W5 [get_ports {rf_adc_data[13]}]
set_property PACKAGE_PIN W6 [get_ports {rf_adc_data[12]}]
set_property PACKAGE_PIN W7 [get_ports {rf_adc_data[11]}]
set_property PACKAGE_PIN V7 [get_ports {rf_adc_data[10]}]
set_property PACKAGE_PIN W8 [get_ports {rf_adc_data[9]}]
set_property PACKAGE_PIN V8 [get_ports {rf_adc_data[8]}]
set_property PACKAGE_PIN Y10 [get_ports {rf_adc_data[7]}]
set_property PACKAGE_PIN Y11 [get_ports {rf_adc_data[6]}]
set_property PACKAGE_PIN W10 [get_ports {rf_adc_data[5]}]
set_property PACKAGE_PIN W11 [get_ports {rf_adc_data[4]}]
set_property PACKAGE_PIN W12 [get_ports {rf_adc_data[3]}]
set_property PACKAGE_PIN V12 [get_ports {rf_adc_data[2]}]
set_property PACKAGE_PIN Y5 [get_ports {rf_adc_data[1]}]
set_property PACKAGE_PIN Y6 [get_ports {rf_adc_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rf_adc_dither]
set_property IOSTANDARD LVCMOS33 [get_ports rf_adc_overflow]
set_property IOSTANDARD LVCMOS33 [get_ports rf_adc_random]
set_property PACKAGE_PIN Y8 [get_ports rf_adc_dither]
set_property PACKAGE_PIN U6 [get_ports rf_adc_overflow]
set_property PACKAGE_PIN U5 [get_ports rf_adc_random]

set_property IOSTANDARD LVCMOS33 [get_ports af_bclk]
set_property IOSTANDARD LVCMOS33 [get_ports af_lrclk]
set_property IOSTANDARD LVCMOS33 [get_ports af_mclk]
set_property PACKAGE_PIN W17 [get_ports af_bclk]
set_property PACKAGE_PIN W18 [get_ports af_lrclk]
set_property PACKAGE_PIN AA18 [get_ports af_mclk]
set_property IOSTANDARD LVCMOS33 [get_ports af_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports af_i2c_sda_io]
set_property PACKAGE_PIN Y16 [get_ports af_i2c_scl_io]
set_property PACKAGE_PIN W16 [get_ports af_i2c_sda_io]

set_property PACKAGE_PIN W20 [get_ports af_dac_data]
set_property IOSTANDARD LVCMOS33 [get_ports af_dac_data]

set_property IOSTANDARD LVCMOS33 [get_ports {o_dacClk[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oS_dacData[0]}]
set_property PACKAGE_PIN V5 [get_ports {o_dacClk[0]}]
set_property PACKAGE_PIN AA9 [get_ports {oS_dacData[13]}]
set_property PACKAGE_PIN AA8 [get_ports {oS_dacData[12]}]
set_property PACKAGE_PIN AB10 [get_ports {oS_dacData[11]}]
set_property PACKAGE_PIN AB9 [get_ports {oS_dacData[10]}]
set_property PACKAGE_PIN U4 [get_ports {oS_dacData[8]}]
set_property PACKAGE_PIN AB7 [get_ports {oS_dacData[7]}]
set_property PACKAGE_PIN AB6 [get_ports {oS_dacData[6]}]
set_property PACKAGE_PIN AB5 [get_ports {oS_dacData[5]}]
set_property PACKAGE_PIN AB4 [get_ports {oS_dacData[4]}]
set_property PACKAGE_PIN T4 [get_ports {oS_dacData[9]}]
set_property PACKAGE_PIN Y4 [get_ports {oS_dacData[3]}]
set_property PACKAGE_PIN AA4 [get_ports {oS_dacData[2]}]
set_property PACKAGE_PIN AB2 [get_ports {oS_dacData[1]}]
set_property PACKAGE_PIN AB1 [get_ports {oS_dacData[0]}]
set_property PACKAGE_PIN L18 [get_ports cw_key_n]
set_property IOSTANDARD LVCMOS33 [get_ports cw_key_n]

set_property PACKAGE_PIN U7 [get_ports {o_dacMode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dacMode[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[0]}]
set_property PACKAGE_PIN M20 [get_ports {debug_leds[7]}]
set_property PACKAGE_PIN L22 [get_ports {debug_leds[6]}]
set_property PACKAGE_PIN P18 [get_ports {debug_leds[5]}]
set_property PACKAGE_PIN P21 [get_ports {debug_leds[4]}]
set_property PACKAGE_PIN M19 [get_ports {debug_leds[3]}]
set_property PACKAGE_PIN L21 [get_ports {debug_leds[2]}]
set_property PACKAGE_PIN P17 [get_ports {debug_leds[1]}]
set_property PACKAGE_PIN P20 [get_ports {debug_leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CODEC_ADC_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports CODEC_BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CODEC_DAC_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports CODEC_LRCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CODEC_MCLK]
set_property PACKAGE_PIN W21 [get_ports CODEC_ADC_DATA]
set_property PACKAGE_PIN W17 [get_ports CODEC_BCLK]
set_property PACKAGE_PIN W20 [get_ports CODEC_DAC_DATA]
set_property PACKAGE_PIN W18 [get_ports CODEC_LRCLK]
set_property PACKAGE_PIN AA18 [get_ports CODEC_MCLK]
set_property OFFCHIP_TERM NONE [get_ports CODEC_BCLK]
set_property OFFCHIP_TERM NONE [get_ports CODEC_DAC_DATA]
set_property OFFCHIP_TERM NONE [get_ports CODEC_LRCLK]
set_property OFFCHIP_TERM NONE [get_ports CODEC_MCLK]

set_property IOSTANDARD LVCMOS33 [get_ports af_adc_data]
set_property PACKAGE_PIN W21 [get_ports af_adc_data]

set_property PACKAGE_PIN M21 [get_ports i_ptt_n]
set_property IOSTANDARD LVCMOS33 [get_ports i_ptt_n]
set_property PULLUP true [get_ports i_ptt_n]

set_property PACKAGE_PIN R20 [get_ports i_ptt_cw_n]
set_property IOSTANDARD LVCMOS33 [get_ports i_ptt_cw_n]
set_property PULLUP true [get_ports i_ptt_cw_n]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN R18 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN N19 [get_ports uart_rtl_0_txd]




set_property OFFCHIP_TERM NONE [get_ports gpio_rs485_rw_tri_o[0]]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rs485_rw_tri_o[0]}]
set_property PACKAGE_PIN J18 [get_ports {gpio_rs485_rw_tri_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rs485_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rs485_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rs485_tri_io[0]}]
set_property PACKAGE_PIN K18 [get_ports {gpio_rs485_tri_io[2]}]
set_property PACKAGE_PIN J16 [get_ports {gpio_rs485_tri_io[1]}]
set_property PACKAGE_PIN J18 [get_ports {gpio_rs485_tri_io[0]}]

set_property PACKAGE_PIN N17 [get_ports eeprom_iic_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports eeprom_iic_scl_io]
set_property PACKAGE_PIN L17 [get_ports eeprom_iic_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports eeprom_iic_sda_io]

set_property PACKAGE_PIN J17 [get_ports {gpio_rs485_tri_io[3]}]
set_property PACKAGE_PIN M17 [get_ports {gpio_rs485_tri_io[4]}]
set_property PACKAGE_PIN N18 [get_ports {gpio_rs485_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rs485_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rs485_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rs485_tri_io[3]}]

set_property OFFCHIP_TERM NONE [get_ports eeprom_iic_scl_io]
set_property OFFCHIP_TERM NONE [get_ports eeprom_iic_sda_io]
set_property OFFCHIP_TERM NONE [get_ports Link_Active[0]]
set_property OFFCHIP_TERM NONE [get_ports Link_Activity[0]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rs485_tri_io[5]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rs485_tri_io[4]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rs485_tri_io[3]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rs485_tri_io[2]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rs485_tri_io[1]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rs485_tri_io[0]]

set_property PACKAGE_PIN AA19 [get_ports encoder_a]
set_property PACKAGE_PIN Y19 [get_ports encoder_b]
set_property IOSTANDARD LVCMOS33 [get_ports encoder_a]
set_property IOSTANDARD LVCMOS33 [get_ports encoder_b]

set_property OFFCHIP_TERM NONE [get_ports LED_Display_Blank]
set_property OFFCHIP_TERM NONE [get_ports LED_Display_Clock]
set_property OFFCHIP_TERM NONE [get_ports LED_Display_Data]
set_property OFFCHIP_TERM NONE [get_ports LED_Display_Latch]
set_property OFFCHIP_TERM NONE [get_ports af_dac_data]
set_property OFFCHIP_TERM NONE [get_ports debug_leds[7]]
set_property OFFCHIP_TERM NONE [get_ports debug_leds[6]]
set_property OFFCHIP_TERM NONE [get_ports debug_leds[5]]
set_property OFFCHIP_TERM NONE [get_ports debug_leds[4]]
set_property OFFCHIP_TERM NONE [get_ports debug_leds[3]]
set_property OFFCHIP_TERM NONE [get_ports debug_leds[2]]
set_property OFFCHIP_TERM NONE [get_ports debug_leds[1]]
set_property OFFCHIP_TERM NONE [get_ports debug_leds[0]]
set_property PULLDOWN true [get_ports {rf_adc_data[15]}]
set_property PULLDOWN true [get_ports {rf_adc_data[14]}]
set_property PULLDOWN true [get_ports {rf_adc_data[13]}]
set_property PULLDOWN true [get_ports {rf_adc_data[12]}]
set_property PULLDOWN true [get_ports {rf_adc_data[11]}]
set_property PULLDOWN true [get_ports {rf_adc_data[10]}]
set_property PULLDOWN true [get_ports {rf_adc_data[9]}]
set_property PULLDOWN true [get_ports {rf_adc_data[8]}]
set_property PULLDOWN true [get_ports {rf_adc_data[7]}]
set_property PULLDOWN true [get_ports {rf_adc_data[6]}]
set_property PULLDOWN true [get_ports {rf_adc_data[5]}]
set_property PULLDOWN true [get_ports {rf_adc_data[4]}]
set_property PULLDOWN true [get_ports {rf_adc_data[3]}]
set_property PULLDOWN true [get_ports {rf_adc_data[2]}]
set_property PULLDOWN true [get_ports {rf_adc_data[1]}]
set_property PULLDOWN true [get_ports {rf_adc_data[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
